
const HTTP_OK = 200;
const HTTP_NOT_FOUND = 404;
const HTTP_UNAUTHORIZED = 401;
const HTTP_BAD_REQUEST = 400;
const SECOND_IN_MILLIE = 1000;
const DATE_FORMAT = 'YYYY-MM-DD';

const INVALID_OBJECT_ID = '123456789012';

export const Constants = {HTTP_OK,
  HTTP_BAD_REQUEST,
  HTTP_NOT_FOUND,
  HTTP_UNAUTHORIZED,
  SECOND_IN_MILLIE,
  DATE_FORMAT,
  INVALID_OBJECT_ID};
