
const HTTP_OK = 200;
const HTTP_NOT_FOUND = 404;
const HTTP_BAD_REQUEST = 400;
const SECOND_IN_MILLIE = 1000;
const DATE_FORMAT = 'YYYY-MM-DD';

export const Constants = {HTTP_OK,
  HTTP_BAD_REQUEST,
  HTTP_NOT_FOUND,
  SECOND_IN_MILLIE,
  DATE_FORMAT};
